-- ════════════════════════════════════════════════════════════════════════
-- Riddhi Siddhi Designers — starter content (optional)
--
-- Generated by scripts/generate-seed.mjs. Run once after the schema
-- migration. Inserts the nine portfolio categories and the six DEMO projects
-- (is_placeholder = true, representative stock imagery) so the site is not
-- empty on day one. Replace or delete the demo projects from the admin panel.
-- Re-running is safe: existing slugs are left untouched.
-- ════════════════════════════════════════════════════════════════════════

begin;

insert into public.categories (name, slug, sort_order) values
  ('Residential', 'residential', 10),
  ('Commercial', 'commercial', 20),
  ('Interior', 'interior', 30),
  ('Retail', 'retail', 40),
  ('Hospitality', 'hospitality', 50),
  ('Warehouse', 'warehouse', 60),
  ('Corporate', 'corporate', 70),
  ('Visualization', 'visualization', 80),
  ('Other', 'other', 90)
on conflict (slug) do nothing;

-- Residence (residential) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Residence', 'residential', c.id, null, null, null, null,
  'Homes shaped around light, privacy and the rhythm of a family’s day.',
  'A residential commission begins with how a household actually lives — where mornings are spent, where people gather, and where they withdraw.',
  'Orientation — Rooms placed to receive the right light at the right hour, and shaded from the harshest.

Threshold — A considered sequence from street to home — gate, court, door, room.

Material — A restrained palette that is warm to the hand and ages with grace.',
  'https://images.unsplash.com/photo-1711963224442-f6eb1329e8c6', 'Brick walls and a tree around an open courtyard in a contemporary house', 'published', true, 10, true, now()
from public.categories c
where c.slug = 'residential'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1711963225994-e34c729579f9', 'A living room framed by a brick jaali shelf wall', 'Living — representative image', 0),
  ('image', 'https://images.unsplash.com/photo-1711963224486-99a19022f305', 'A perforated brick screen beside a planted courtyard', 'Screen and court', 1),
  ('image', 'https://images.unsplash.com/photo-1711963225980-dbc5adcf2e0d', 'A white sofa set against timber shelving and exposed brick', null, 2),
  ('image', 'https://images.unsplash.com/photo-1601993957728-1e56ab70c5a8', 'A plastered stair rising towards soft daylight', 'Stair', 3),
  ('image', 'https://images.unsplash.com/photo-1628012209120-d9db7abf7eab', 'White cubic volumes of a contemporary house against the sky', 'Massing', 4),
  ('image', 'https://images.unsplash.com/photo-1600585153490-76fb20a32601', 'A dark timber house with tall lit openings at dusk', 'Evening', 5),
  ('visualization', 'https://images.unsplash.com/photo-1653164494885-a8526f62678c', 'A white model house on a pale base', null, 6)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'residential'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

-- Workplace (commercial) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Workplace', 'commercial', c.id, null, null, null, null,
  'Workplaces planned around focus, collaboration and arrival.',
  'A workplace is a daily ritual for the people inside it. Its plan should make concentration easy, conversation natural and arrival memorable.',
  'Zoning — Quiet, collaborative and social settings arranged as a legible sequence.

Daylight — Work placed along the light; support spaces gathered at the core.

Identity — Material and detail that express the organisation without signage.',
  'https://images.unsplash.com/photo-1643267514395-b36b3f7e8281', 'An open workplace with a long glazed wall facing greenery', 'published', true, 20, true, now()
from public.categories c
where c.slug = 'commercial'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1705909770198-7e83c24e1616', 'A quiet work lounge with sculptural chairs and timber', 'Lounge', 0),
  ('image', 'https://images.unsplash.com/photo-1693625700727-b548ca8f5679', 'A meeting room with a long table and floor-to-ceiling glass', 'Meeting and studio', 1),
  ('image', 'https://images.unsplash.com/photo-1497366616365-e78dd380d3dd', 'A concrete-walled studio space with a long shared table', null, 2),
  ('image', 'https://images.unsplash.com/photo-1496236436299-cde70e3587cf', 'A facade of deep vertical fins casting hard shadows', 'Facade study', 3),
  ('visualization', 'https://images.unsplash.com/photo-1672669092491-ac5a210747bc', 'A white massing model of a cluster of buildings', null, 4)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'commercial'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

-- Hospitality (hospitality) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Hospitality', 'hospitality', c.id, null, null, null, null,
  'Places of welcome, where atmosphere is designed as carefully as function.',
  'In hospitality, the first impression is spatial — the volume of a room, the warmth of its light, the weight of a door handle.',
  'Arrival — A choreographed sequence from street to table or room.

Atmosphere — Light designed in layers, so the room changes from day to night.

Durability — Surfaces that withstand daily use and still feel generous.',
  'https://images.unsplash.com/photo-1650490534612-d9ba46776916', 'A low-lit dining room under a slatted timber ceiling', 'published', true, 30, true, now()
from public.categories c
where c.slug = 'hospitality'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1660557989695-14fac79c086d', 'A stone reception desk with warm, low lighting', 'Reception', 0),
  ('image', 'https://images.unsplash.com/photo-1759038086832-795644825e3a', 'A curved timber wall wrapping a hotel lobby', 'Lobby', 1),
  ('image', 'https://images.unsplash.com/photo-1650490632010-e18cbb694dd1', 'A dark bar interior with warm wall lighting', 'Bar and corridor', 2),
  ('image', 'https://images.unsplash.com/photo-1558277872-bb3f50054da2', 'A long, softly lit hotel corridor', null, 3),
  ('image', 'https://images.unsplash.com/photo-1628630468252-a086c2bc7255', 'A live-edge timber table in a hotel lounge', 'Lounge', 4),
  ('visualization', 'https://images.unsplash.com/photo-1735448213858-6bdfdf78967a', 'A white interior model showing layered screens and openings', null, 5)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'hospitality'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

-- Interior (interior) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Interior', 'interior', c.id, null, null, null, null,
  'Rooms resolved to the detail — layout, material, light and the objects within.',
  'An interior is experienced at arm’s length. Proportion, light and texture matter as much as the plan.',
  'Light — Natural light protected and drawn deeper into the room.

Joinery — Storage and furniture built in, so the room stays calm.

Texture — Plaster, timber and stone layered for warmth without clutter.',
  'https://images.unsplash.com/photo-1711891391309-c1f93b463c7e', 'A calm room crossed by geometric bands of light and shadow', 'published', true, 40, true, now()
from public.categories c
where c.slug = 'interior'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1704458162479-42b5e0023c39', 'Lime-plastered arches and timber doors in soft light', 'Arches', 0),
  ('image', 'https://images.unsplash.com/photo-1700809887581-c41c239e808e', 'Timber slats and a single pendant light in a warm interior', 'Timber and light', 1),
  ('image', 'https://images.unsplash.com/photo-1590411255052-ea52fd44c531', 'A chair beneath a shaft of light from a skylight', 'Skylight and window', 2),
  ('image', 'https://images.unsplash.com/photo-1610123172763-1f587473048f', 'A living space with a large window and low warm furniture', null, 3),
  ('image', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6', 'A neutral living room with low furniture and natural textures', 'Living', 4),
  ('visualization', 'https://images.unsplash.com/photo-1735448213858-6bdfdf78967a', 'A white interior model showing layered screens and openings', null, 5)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'interior'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

-- Retail (retail) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Retail', 'retail', c.id, null, null, null, null,
  'Retail environments tuned to the product — circulation, display and light.',
  'A shop is a stage for its product. The plan sets the pace of browsing; light and material set the tone of the brand.',
  'Sequence — A route that reveals the collection gradually.

Display — Fixtures designed as architecture, not furniture.

Light — Accent and ambient light balanced to flatter the product.',
  'https://images.unsplash.com/photo-1718985342149-7178154e0aee', 'A retail interior with timber shelving and hanging garments', 'published', false, 50, true, now()
from public.categories c
where c.slug = 'retail'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1769107805465-bfd41863f1a0', 'A minimal garment rail against a pale plaster wall', 'Rail', 0),
  ('image', 'https://images.unsplash.com/photo-1769107805412-90d9191d53e9', 'Floating white shelves holding a few objects', 'Shelving and display', 1),
  ('image', 'https://images.unsplash.com/photo-1644562278850-0181eb7f587a', 'Backlit timber display shelving in a boutique', null, 2),
  ('visualization', 'https://images.unsplash.com/photo-1653164488636-7407bec89281', 'A white model of a cantilevered pavilion', null, 3)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'retail'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

-- Visualization (visualization) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select 'Visualization', 'visualization', c.id, null, null, null, null,
  'Seeing a space before it is built — form, light and material, tested in three dimensions.',
  'Visualization turns drawings into experience. Massing, daylight and material can be judged by eye, long before construction begins.',
  'Massing — Early volumetric studies to test scale and placement.

Daylight — Light studied through the day and across the seasons.

Material — Finishes compared side by side in context.',
  'https://images.unsplash.com/photo-1631454965644-00510875561f', 'A timber architectural model with angled fins on a dark ground', 'published', false, 60, true, now()
from public.categories c
where c.slug = 'visualization'
on conflict (slug) do nothing;

insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
  ('image', 'https://images.unsplash.com/photo-1672669092491-ac5a210747bc', 'A white massing model of a cluster of buildings', 'Massing study', 0),
  ('image', 'https://images.unsplash.com/photo-1653164488636-7407bec89281', 'A white model of a cantilevered pavilion', 'Form studies', 1),
  ('image', 'https://images.unsplash.com/photo-1653164494885-a8526f62678c', 'A white model house on a pale base', null, 2),
  ('image', 'https://images.unsplash.com/photo-1735448213858-6bdfdf78967a', 'A white interior model showing layered screens and openings', 'Interior study', 3),
  ('visualization', 'https://images.unsplash.com/photo-1672669092491-ac5a210747bc', 'A white massing model of a cluster of buildings', null, 4),
  ('visualization', 'https://images.unsplash.com/photo-1653164488636-7407bec89281', 'A white model of a cantilevered pavilion', null, 5)
) as m(kind, url, alt, caption, sort_order)
where pr.slug = 'visualization'
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);

commit;
