/**
 * Generates supabase/seed.sql from the same seed data the local preview uses
 * (src/lib/cms/seed-data.ts → src/content/projects.ts), so both stay in sync.
 *
 *   node scripts/generate-seed.mjs
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = mkdtempSync(join(tmpdir(), "rsd-seed-"));

// Transpile the three modules involved and rewrite their imports to relative .mjs files.
const files = {
  "images.mjs": "src/content/images.ts",
  "projects.mjs": "src/content/projects.ts",
  "seed-data.mjs": "src/lib/cms/seed-data.ts",
};
for (const [target, source] of Object.entries(files)) {
  const code = ts.transpileModule(readFileSync(join(root, source), "utf8"), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  }).outputText
    .replace(/from "\.\/images"/g, 'from "./images.mjs"')
    .replace(/from "@\/content\/projects"/g, 'from "./projects.mjs"');
  writeFileSync(join(out, target), code);
}

const { seedCategories, seedProjects } = await import(pathToFileURL(join(out, "seed-data.mjs")).href);
rmSync(out, { recursive: true, force: true });

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const categories = seedCategories();
const projects = seedProjects();
const slugOfCategory = Object.fromEntries(categories.map((c) => [c.id, c.slug]));

let sql = `-- ════════════════════════════════════════════════════════════════════════
-- Riddhi Siddhi Designers — starter content (optional)
--
-- Generated by scripts/generate-seed.mjs. Run once after the schema
-- migration. Inserts the nine portfolio categories and the six DEMO projects
-- (is_placeholder = true, representative stock imagery) so the site is not
-- empty on day one. Replace or delete the demo projects from the admin panel.
-- Re-running is safe: existing slugs are left untouched.
-- ════════════════════════════════════════════════════════════════════════

begin;

insert into public.categories (name, slug, sort_order) values
${categories.map((c) => `  (${q(c.name)}, ${q(c.slug)}, ${c.sortOrder})`).join(",\n")}
on conflict (slug) do nothing;
`;

for (const p of projects) {
  sql += `
-- ${p.title} (${slugOfCategory[p.categoryId]}) — demo placeholder
insert into public.projects (
  title, slug, category_id, location, year, client_name, project_status, summary, description, design_approach,
  cover_url, cover_alt, visibility, featured, sort_order, is_placeholder, published_at
)
select ${q(p.title)}, ${q(p.slug)}, c.id, ${q(p.location)}, ${q(p.year)}, ${q(p.clientName)}, ${q(p.projectStatus)},
  ${q(p.summary)},
  ${q(p.description)},
  ${q(p.designApproach)},
  ${q(p.coverUrl)}, ${q(p.coverAlt)}, 'published', ${p.featured}, ${p.sortOrder}, true, now()
from public.categories c
where c.slug = ${q(slugOfCategory[p.categoryId])}
on conflict (slug) do nothing;
`;
  if (p.media.length) {
    sql += `
insert into public.project_media (project_id, kind, url, alt, caption, sort_order)
select pr.id, m.kind, m.url, m.alt, m.caption, m.sort_order
from public.projects pr
cross join (values
${p.media.map((m) => `  (${q(m.kind)}, ${q(m.url)}, ${q(m.alt)}, ${q(m.caption)}, ${m.sortOrder})`).join(",\n")}
) as m(kind, url, alt, caption, sort_order)
where pr.slug = ${q(p.slug)}
  and not exists (select 1 from public.project_media pm where pm.project_id = pr.id);
`;
  }
}

sql += "\ncommit;\n";
mkdirSync(join(root, "supabase"), { recursive: true });
writeFileSync(join(root, "supabase", "seed.sql"), sql);
console.log(`supabase/seed.sql written — ${categories.length} categories, ${projects.length} demo projects.`);
